-- GROUP FUNCTIONS--
-- RETURN ONE RESULT PER GROUP OF ROW--

SELECT MAX(COST) AS PMAX FROM BOOKS;

SELECT MIN(COST) AS PMIN FROM BOOKS;

SELECT AVG(COST) AS PAVG FROM BOOKS;

SELECT SUM(COST) AS PSUN FROM BOOKS;

SELECT COUNT(*)  AS PCOUNT FROM BOOKS;

SELECT COUNT(DISCOUNT)  AS PCOUNT FROM BOOKS;

SELECT CATEGORY, AVG(RETAIL)
FROM BOOKS
GROUP BY CATEGORY;

SELECT CATEGORY, SUM(DISCOUNT)
FROM BOOKS
GROUP BY CATEGORY;

SELECT TITLE, AVG(RETAIL)
FROM BOOKS
GROUP BY TITLE;

SELECT * FROM BOOKS;

